[village]
	#The chance (as a percentage) that a house slot in a village will be replaced with one of this mod's custom buildings.
	#0 = vanilla houses only, 100 = only this mod's buildings will spawn.
	#The first number in the define in range is the dynamic village spawn probability.
	# Default: 15
	# Range: 0 ~ 100
	buildingSpawnChancePercent = 15
