#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 29 17:41:47 NOVT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
